### ISSUE TITLE
Created component that emits an event in "componentActivate" doesn't work

### ISSUE THREAD

**Issue by Eliott-Guevel** [OpenSmock/Molecule#102]
In a situation where 2 components are linked, with one emitting an event at its activation and the other listening and treating it whenever it's received, the event is never received even though it was correctly sent, but sending it manually through the Property Inspector of the first component (written in the form of get...Events attribute) works as intended.

To fix this problem, it's necessary to change the order of some functions' execution in the `activateComponent: named:` method located in the `MolHomeServices` class, which is to say that these lines of code:
```
MolComponentManager default locatorServices
		resolveWaitingSubscriptions: component.
```
should be put before the activation of a component:
`component componentActivate.`
in order to resolve this conflict, since the events are not correctly linked between before the complete execution of the `activateComponent: named:` method

**Comment by labordep** [comment]
Fixed in : https://github.com/OpenSmock/Molecule/pull/104
