### ISSUE TITLE
Component name generation to quickly start a lot of components

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Molecule#140]
Use case : for starting examples component quickly.

Actually: 

```
MolComponentImpl>>start "start with default name"
MolComponentImpl>>start: aComponentName "start with a specific name"
```

Proposition:

```
MolComponentImpl>>startUnique "start with a unique name"
```

The idea is to be sure that the generated name is unique (the generation can be managed by the component manager).
I'm not sure if "unique" is the good word.

**Comment by labordep** [comment]
@ELePors can I have your opinion ?

**Comment by labordep** [comment]
New proposition to be not ambigus with a possible unique instance:

`MolComponentImpl>>startWithUniqueName`

**Comment by ELePors** [comment]
I'm Ok... just to have another proposition ? :

```MolComponentImpl>>startWithGeneratedName```

Because generated name is implicitely not colliding existing component instance names... 
and we explicitely tell to the coder that a name is generated.

**Comment by labordep** [comment]
Ok!
We will do that for start and instantiate methods.
We need to check, at the generation, if the name is not already used by another component implementation of the same class.
This can be the case when a previous implementation is started with a specific name.
