### ISSUE TITLE
No auto generation when adding new events or services on component type

### ISSUE THREAD

**Issue by LouisePla** [OpenSmock/Molecule#148]
When I add events or services to a component type Trait, there is no auto generation in the component implementation.

Use case to reproduce on a new Pharo 11 - 64 bit image :
1 - Load Molecule on Pharo image
```
Metacello new
   baseline: 'Molecule';
   repository: 'github://OpenSmock/Molecule:main/src';
   load.
```
   
2 - Create a MolGeneratorBugTest type
```
Trait named: #MolGeneratorBugTest
	uses: MolComponentType
	instanceVariableNames: ''
	package: 'Molecule-Examples-test'
```
	
3 - Create an event MolGeneratorBugTestEvents
```
Trait named: #MolGeneratorBugTestEvents
	uses: MolComponentEvents
	instanceVariableNames: ''
	package: 'Molecule-Examples-test'
```
	
4- Create an implementation MolGeneratorBugTestImpl for MolGeneratorBugTest 
```
MolAbstractComponentImpl subclass: #MolGeneratorBugTestImpl
	uses: MolGeneratorBugTest
	instanceVariableNames: ''
	classVariableNames: ''
	package: 'Molecule-Examples-test'
```

5 - Add the event MolGeneratorBugTestEvents into MolGeneratorBugTest  type
```
producedComponentEvents
	<componentContract>
	^ {MolGeneratorBugTestEvents} 
```

-> The event notifier is not generated into the implementation
![image](https://github.com/OpenSmock/Molecule/assets/123971303/dc6bddd6-d763-471c-bf3c-132943db4664)

**Comment by labordep** [comment]
Thanks @LouisePla!

**Comment by labordep** [comment]
@LouisePla, this is a bug.
Normaly you should have the notifier corresponding to your produced events interface, even if your events interface is empty.
Do you have some methods in your Events interface in this example (I suppose no) ?
