### ISSUE TITLE
Can't know at the moment which Types use an interface

### ISSUE THREAD

**Issue by Eliott-Guevel** [OpenSmock/Molecule#164]
Currently, every interface has a `users` field to know which implementation use it.
It would be useful to have a similar field for Types, and a way to distinguish from when they're required or offered.

**Comment by labordep** [comment]
Hi @Eliott-Guevel ,

You need something like that:

```smalltalk
MyServicesTrait offeredTypes.
MyServicesTrait requiredTypes.
```

?

**Comment by Eliott-Guevel** [comment]
Exactly, and returning it as an OrderedCollection would be the easiest way to handle it in my opinion

**Comment by Eliott-Guevel** [comment]
I think so, since required and offered are both the generic versions of respectively produced and consumed and provided and used

**Comment by labordep** [comment]
I'm going to implement that: `MolUtils offeredTypes: MolUnusedServices`
Because this is a tool and I prefer have only domain behavior in each Services/Event/Param Traits.
