### ISSUE TITLE
Add announcers to know when a Molecule Component is started and stopped

### ISSUE THREAD

**Issue by Eliott-Guevel** [OpenSmock/Molecule#170]
A GitHub search of its repository shows that no such option exists at the moment:
![announcer](https://github.com/OpenSmock/Molecule/assets/76944457/327059d0-eb56-48dc-9980-e4127df5a66c)

Announcers would be useful for the visualization option currently developed in Molecule-Incubator

**Comment by labordep** [comment]
Hi @Eliott-Guevel, this code is the internal mecanism of Molecule to be notified when classes change. This is not related to component life-cycle but related to live-coding features.

I think we don't have Molecule Announcers and it should be good to propose that for monitoring a Molecule system. 
This can be for example:
- ComponentInitialize
- ComponentActivate
- ComponentPassivate
- ComponentRemove

**Comment by labordep** [comment]
We have this:
```
MolHomeServices>>instantiateComponent: aComponentClass named: aName
(...)
      component triggerEvent: #instantiateComponent with: component.
(...)

MolHomeServices>>activateComponent: aComponentClass named: aName
(...)
      component triggerEvent: #activateComponent with: component.
(...)

etc.
```
This is an old mecanism, probably not used because no tests and no references to it. 
@ELePors I thinks we can replace this old (and not used) mecanism by new system Announcers, what is your opinion?

**Comment by ELePors** [comment]
Hi @labordep and @Eliott-Guevel 

Whe should try to create Announcement subclasses : 
```md
MolComponentAbastractAnnoucement
├── MolComponentActivated
├── MolComponentInstanciated
├── ...
```
with a #component:  method implemented to indicate which component is related to the announcement.

The MolComponentManager should do announcements...
and others should listen to these announcements...
