### ISSUE TITLE
Contract method not generated in Pharo 7

### ISSUE THREAD

**Issue by labordep** [OpenSmock/Molecule#2]
Since Pharo 7.0, contract methods are not automaticaly generated anymore. Probably a problem with Traits in Pharo 7.0 with Pragma.

**Temporary solution :** 
Use `MolComponentFactory defineComponent: YourComponentImpl` for generate your contract methods from required Traits.

**Comment by nolwennfournier** [comment]
`MolComponentFactory >> defineComponent:` is called when a method with `<componentContract>`  is updated.

First, the `PragmaCollector` which is listening `<componentContract>`  is initialized with a `MolComponentFactory`. We have to instanciate it to initialize the pragma. It has been corrected.

Then, when you create your component implementation by adding a subclass of `MolAbstractComponentImpl` or using `MolComponentImpl` trait, none of `<componentContract>` methods (of your ComponentType trait) is updated. So the method `MolComponentFactory >> defineComponent:` is not called.

We have to continue to use `MolComponentFactory >> defineComponent:`...
