### ISSUE TITLE
enhancement  - Better world menu

### ISSUE THREAD

**Issue by Nyan11** [OpenSmock/Molecule#47]
I found two ways to improve the world menu for molecule.

## Put molecule in the correct submenu
Maybe we should put molecule wordmenu in the Library worldmenu.
Roassal3 is present in the Library menu and not directly on the main MenuBar of the pharo world.

The description for Library is : "Third party tools and applications".
(The menu for Library is in package Morphic-Core > WorldState class side > LibraryWordMenuOn).

If we put the molecule menu under Library, we should add also an icon to it (for example the MolIcon).

![worldmenu-roassal](https://user-images.githubusercontent.com/34318678/149562543-3665a859-03d1-4dcb-a0f3-5f66b66095e3.png)
[Roassal3 under Library]

## better method naming 
The current world menu for molecule doesn't seem to follow any clear structure in its methods names (inside the browser).

The world menu of molecule is present in 2 packages : 
- Molecule-IDE >>> MolWorld
- Molecule-IDE-Incubators >>> MolWorldActionsMenu

The menu and the differents submenus methods are not explicit about their content and/or their position in the main menu. By making the methods names more explicits, we could edit the menu more rapidly in the future.

The Roassal3 world menu use a different convention to labels the methods : menu{position}{title/description}On.

I suggest we could rename the menus of molecule by :
### in Molecule-IDE >>> MolWorld
- menuCommandOn -> menu00moleculeOn
- currentComponentSystem -> menu01currentComponentSystemOn
- menuDebugOn -> menu02debugOn
- componentManagerCleanUp -> menu04componentManagerCleanUpOn
- menuExamplesOn -> menu05examplesOn
- menuGithubOn -> menu06githubOn
- menuReportBugOn -> menu07reportBugOn
.
- defineComponentOn -> debugMenu01defineComponentOn
- toggleMolLogsOn -> debugMenu02toggleMolLogsOn
- toggleDynamicContractUpdate -> debugMenu03toggleDynamicContractUpdate
- inspectAllComponentInstances -> debugMenu04inspectAllComponentInstances
- etc ...

### in Molecule-IDE-Incubators >>> MolWorldActionsMenu
- menuActionsOn -> menu03ActionsOn (or menu03IncubatorToolsOn)
- menuInspectOn -> actionsMenu01inspectOn (+ Classify method as "menu - actions")
- menuSearchOn -> actionsMenu02searchOn (+ Classify method as "menu - actions")
- menuCreateOn -> actionsMenu03createOn (+ Classify method as "menu - actions")

![browser-molecule](https://user-images.githubusercontent.com/34318678/149562690-07f04680-e010-49eb-b433-cfd1661f5dd0.png)
[Methods names of molecule are less explicit than Roassal3]
![browser-roassal](https://user-images.githubusercontent.com/34318678/149562716-bdc8e98b-0eba-45c5-8f98-e4cf0034d19a.png)

**Comment by Nyan11** [comment]
The menu should also use 'group' signal to separate the different sections.
See as an example in Morphic-core -> (class side) WorldState >>> browseWorldMenuOn.

**Comment by labordep** [comment]
Thanks Nyan11, this is some good propositions to enhance the UX of Molecule.
I'm starting to work on it : 

- [ ] Put molecule in the correct submenu
- [ ] better method naming
- [ ] The menu should also use 'group' signal to separate the different sections.
