### ISSUE TITLE
[IDE] bug - world menu - "No Components are running"

### ISSUE THREAD

**Issue by Nyan11** [OpenSmock/Molecule#48]
There is 2 bugs on molecule world menu.

When you start a new molecule component, the world menu doesn't update and still display "No Components are running".

![molecule-bug-no-run](https://user-images.githubusercontent.com/34318678/149580061-0a8ee2c1-feb9-4aa1-9d9e-f5df1b3938ec.png)
[molecule components is running but the world menu say other wise]

## To reproduce
- Run `MolGPSExampleLauncher start.` in the playground.
- Then just click on molecule menu (menubar of current world). It should display "No Components are running".

It's also possible to trigger another similar bug.

- Run `MolGPSExampleLauncher start.` in the playground.
- Run `MenubarMorph reset.` in the playground. It should have corrected the bug.
- Run  `MolGPSExampleLauncher stop.` in the playground.
- Then just click on molecule menu (menubar of current world). It should display "System is running Components".

## Fix
It can be fixed by triggering the `MenubarMorph reset.`.
![bug-molecule-trigger-reset](https://user-images.githubusercontent.com/34318678/149573713-c4097f1f-4821-4ab4-9b95-82464828c35e.png)

To fix this issue `MenubarMorph reset.` should be trigger every time the number of components running passes from 0 to any > 0, and when the number of components go to any > 0 to 0.

It can be fix in the Molecule Package.
In MolHomeServices >>> activateComponent:named: at the end of the method, if we add the MenubarMorph reset.
In MolHomeServices >>> removeComponent:named: at the end of the method, if we add the MenubarMorph reset.

But, this solution will make `MenubarMorph reset.` for every component added or removed even when the number go from 5 to 6 for example. It should only trigger when the number of components change from 0 to any or any to 0.

**Comment by labordep** [comment]
Hi Nyan11, thanks for the report.
This problem not appear with the contextual Pharo menu (on the left click) : 
![image](https://user-images.githubusercontent.com/49183340/150556636-16dda8cf-f1d7-45b7-892f-40f9e51e37e0.png)

Do you know how this is different ? MenubarMorph>>reset is not called by this way.

**Comment by Nyan11** [comment]
Hi,
The bug is present with the contextual menu if you lock it (with the small circle at the top).
To reproduce :
1) you stop all components running.
2) you open a context menu, and you lock it
3) you start a component
4) the locked menu should display the bug.

The problem is, contextual and world menu are not the same class.
`MenubarMorph` -> top panel, it can access and reset with `MenubarMorph reset.`
`MenuMorph` -> contextual, it can not be access easily and can not be reset easily either.

Solution to fix the locked contextual menu:
1) get all the `MenuMorph` from `self currentworld submorphs`
2) for each : remove the molecule submenu and add create a new submenu molecule.
3) add the new submenu to each `MenuMorph` found.

This is way more complicated and probably not a fix forseen by morphic's dev.

**Comment by labordep** [comment]
Ok ! I think Pharo menus (MenuMorph or MenuBarMorph) are not designed for that use case, in mean dynamically update buttons status. 
This function is a good tool for developper, we need to find a solution to have a speed way to get components and also to have the Molecule system status (Components are running or not).

One off the solutions can be a trigger when a button become visible or when a menu is open. The menu don't need to be updated on the fly but just on the opening. May be there are some Annoucement for do that ?
