### ISSUE TITLE
Bug: different types can be used for the name of a component when creating or calling it

### ISSUE THREAD

**Issue by Samuel29590** [OpenSmock/Molecule#63]
The normal way to name a component is to use a symbol. So when creating it we use a symbol and when we call it elsewhere we also use a symbol (see the following screenshot).

![normal](https://user-images.githubusercontent.com/64481702/179070453-af0749ac-5c26-405a-a19a-a0b6fdcd0d26.png)

The first bug is when creating a component, we can create it using a string and it works (see the following screenshot).

![strange](https://user-images.githubusercontent.com/64481702/179071270-82f8fb97-3771-4be1-ba12-3a47425f5229.png)

The second bug is when we creating a component using a string and also using a string to call it. It doesn't work and the component isn't found (see the following screenshots).

![string](https://user-images.githubusercontent.com/64481702/179072045-6aba8ed4-2658-41c5-8a62-54bcf69f885a.png)
![string bug](https://user-images.githubusercontent.com/64481702/179072054-281d0e4e-4437-42b9-b575-7fdb061d8dd1.png)

**Comment by labordep** [comment]
Thanks @Samuel29590.
In Molecule a component name should be a Symbol. String or another kling of object cannot be autorized to name a component. I will return an "wrong name" Exception in a patch to identify that directlty before the instanciation of a component.

**Comment by labordep** [comment]
There is another sub-bug, when you getTMATimeTraverServicesProvider, Molecule should return to you a "notFoundServicesProvider" and it return "nil". This is not correct. I will check that.

**Comment by labordep** [comment]
Creating #64
