### ISSUE TITLE
Instanciate isn't the correct form

### ISSUE THREAD

**Issue by Eliott-Guevel** [OpenSmock/Molecule#97]
Instanciate is the french form of the verb, instantiate being the english form of the same verb.
Same goes for instanciation that must be changed to instantation.
[Source](https://www.linguee.fr/anglais-francais/traduction/instantiate.html),
it's also worth mentioning that no result comes up while searching for "instanciate" in a web navigator

**Comment by labordep** [comment]
Thanks @Eliott-Guevel, we need to correct that with deprecation tool.

**Comment by labordep** [comment]
There is a problem with tests on Pharo 12 : 

  ✗ #testStopComponentNamed (22ms)
Error: This node doesn't have a parent

Similar to https://github.com/pharo-project/pharo/issues/14697
