### ISSUE TITLE
Putting an empty variable in a component's contract should fail

### ISSUE THREAD

**Issue by Eliott-Guevel** [OpenSmock/Molecule#99]
In Pharo 11, putting an instance variable into one of the parts that make a component's contract (i.e. consumed/producedComponentEvents, used/providedComponentServices) for a given Type automatically creates a get...Notifier method (as expected) in its implementations, but in this case leads to the creation of a getnilNotifier method. This getnilNotifier searches for notifiers `at: nil`, which isn't a trait that uses the MolComponentEvents trait.

Instead of this current behavior, the compilator should return an error when putting an empty instance variable into one or multiple parts of a component's contract.

**Comment by labordep** [comment]
Thanks @Eliott-Guevel !

**Comment by labordep** [comment]
@Eliott-Guevel could you give to me an example ?

**Comment by Eliott-Guevel** [comment]
Putting an empty `game` instance variable for the `GameConsole` type
<img width="620" alt="consumedEvent game" src="https://github.com/OpenSmock/Molecule/assets/76944457/130d58e0-747c-4a90-8995-aca73724d8dc">
leads to the creation of a `getnilSubscriber` method in `SNES` (a `GameConsole` implementation) (after using the define all components option)
<img width="641" alt="getnilsubscriber" src="https://github.com/OpenSmock/Molecule/assets/76944457/6c136ec8-089e-4fcd-99e1-e5cb598b33ae">

**Comment by labordep** [comment]
Ohhh ok :)
We work on it :)

**Comment by labordep** [comment]
Problem when declaring a variable into a Trait class side (for making the test).

**Comment by labordep** [comment]
Bug fixed but this mistake bring some unstability problem of the image.
